### ISSUE TITLE
Aliased variables do not include "mode" name

### ISSUE THREAD

**Issue by slava-class** [mark-nicepants/variables2json-docs#5]
Hi there,

When attempting to deference aliased variables (`isAlias: true`) — the `value` contains `collection` and `name`, but to get there, a mode `name` is also required, if I understand correctly.

So, could mode name be added to aliased values, or am I misunderstanding how aliased variables should be dereferenced?

Thank you!

**Comment by mark-nicepants** [comment]
This is correct, you cannot know the mode in the json because there can be multiple values (1 per mode). 

To look up the correct value, you first need to know all active modes in your application. Only after you know that you can lookup the correct value.

For example when you implement this json in an app or site and you can a collection Theme with modes Light/Dark. The light/dark is configured at runtime and can be changed while the application is running. 

Hope this answers your question.

**Comment by slava-class** [comment]
I see, I think my design has different modes across collections, which caused the confusion. That clears things up, thank you!
